export const CREATE_PARCELS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS parcels (
  objectid         BIGINT PRIMARY KEY,
  pin              TEXT,
  alt_pin          TEXT,
  geom             GEOMETRY,
  lon              DOUBLE,
  lat              DOUBLE,
  site_address     TEXT, site_city TEXT, site_state TEXT, site_zip TEXT,
  municipality     TEXT, township TEXT, jurisdiction TEXT,
  gis_acres        DOUBLE,
  gross_acres      DOUBLE,
  zoning           TEXT,
  class            TEXT,
  emv              DOUBLE,
  eav              DOUBLE,
  land_value       DOUBLE,
  building_value   DOUBLE,
  owner_name       TEXT,
  owner_addr       TEXT, owner_city TEXT, owner_state TEXT, owner_zip TEXT,
  taxbill_name     TEXT, taxbill_addr TEXT, taxbill_csz TEXT, taxbill_year INT,
  date_last_sale   DATE, date_of_sale DATE, gross_sale_price DOUBLE,
  year_built       INT,
  total_sqft       DOUBLE, garage_sqft DOUBLE,
  source_system    TEXT,
  source_url       TEXT,
  retrieved_at     TIMESTAMP,
  source_payload   JSON
);
`;

export const PARCEL_INSERT_COLUMNS = [
  "pin",
  "alt_pin",
  "objectid",
  "geom",
  "lon",
  "lat",
  "site_address",
  "site_city",
  "site_state",
  "site_zip",
  "municipality",
  "township",
  "jurisdiction",
  "gis_acres",
  "gross_acres",
  "zoning",
  "class",
  "emv",
  "eav",
  "land_value",
  "building_value",
  "owner_name",
  "owner_addr",
  "owner_city",
  "owner_state",
  "owner_zip",
  "taxbill_name",
  "taxbill_addr",
  "taxbill_csz",
  "taxbill_year",
  "date_last_sale",
  "date_of_sale",
  "gross_sale_price",
  "year_built",
  "total_sqft",
  "garage_sqft",
  "source_system",
  "source_url",
  "retrieved_at",
  "source_payload",
] as const;
